# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sd_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 535)
        MainWindow.setStyleSheet("QLCDNumber{\n"
"    color: rgb(255, 0, 0);    \n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(110, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 35.78)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(110, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setProperty("value", 35.78)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(110, 340, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setProperty("value", 35.78)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.label.setStyleSheet("QLabel {\n"
"    border: 2px solid black;\n"
"    background-color: cyan;\n"
"    font: bold 16px\n"
"}")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 330, 101, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"    border: 2px solid black;\n"
"    background-color: cyan;\n"
"    font: bold 16px\n"
"}")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 101, 41))
        self.label_5.setStyleSheet("QLabel {\n"
"    border: 2px solid black;\n"
"    background-color: cyan;\n"
"    font: bold 16px\n"
"}")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 50, 121, 111))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(130, 50, 121, 111))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 210, 121, 111))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(130, 210, 121, 111))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_5.setGeometry(QtCore.QRect(130, 370, 121, 111))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_6.setGeometry(QtCore.QRect(10, 370, 121, 111))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 10, 101, 41))
        self.label_4.setStyleSheet("QLabel {\n"
"    border: 2px solid black;\n"
"    background-color: cyan;\n"
"    font: bold 16px\n"
"}")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(370, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("value", 35.78)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_7.setGeometry(QtCore.QRect(390, 50, 121, 111))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_8.setGeometry(QtCore.QRect(270, 50, 121, 111))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 10, 101, 41))
        self.label_6.setStyleSheet("QLabel {\n"
"    border: 2px solid black;\n"
"    background-color: cyan;\n"
"    font: bold 16px\n"
"}")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(620, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("value", 35.78)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_9.setGeometry(QtCore.QRect(640, 50, 121, 111))
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_10.setGeometry(QtCore.QRect(520, 50, 121, 111))
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 390, 141, 61))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 255, 127);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"    font: 63 24pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(300, 190, 81, 31))
        self.comboBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(273, 190, 20, 301))
        self.line.setStyleSheet("QLineEdit{\n"
"    background-color: red;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(280, 170, 481, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(400, 230, 71, 41))
        self.spinBox.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox.setObjectName("spinBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 230, 101, 41))
        self.label_7.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 255, 127);\n"
"    font: bold 12px;\n"
"}")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(400, 280, 71, 41))
        self.spinBox_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 280, 101, 41))
        self.label_8.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 255, 127);\n"
"    font: bold 12px;\n"
"}")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(400, 330, 71, 41))
        self.spinBox_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(290, 330, 101, 41))
        self.label_9.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 170, 127);\n"
"    font: bold 12px;\n"
"}")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 380, 101, 41))
        self.label_10.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 170, 127);\n"
"    font: bold 10px;\n"
"}")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setGeometry(QtCore.QRect(400, 380, 71, 41))
        self.spinBox_4.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(490, 230, 101, 41))
        self.label_11.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 170, 127);\n"
"    font: bold 12px;\n"
"}")
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.spinBox_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_5.setGeometry(QtCore.QRect(600, 230, 71, 41))
        self.spinBox_5.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_6.setGeometry(QtCore.QRect(600, 280, 71, 41))
        self.spinBox_6.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(490, 280, 101, 41))
        self.label_12.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 170, 127);\n"
"    font: bold 10px;\n"
"}")
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.spinBox_7 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_7.setGeometry(QtCore.QRect(600, 330, 71, 41))
        self.spinBox_7.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(490, 330, 101, 41))
        self.label_13.setStyleSheet("QLabel {\n"
"    border: 2px black;\n"
"    background-color: rgb(255, 170, 255);\n"
"    font: bold 10px;\n"
"}")
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuSecond = QtWidgets.QMenu(self.menubar)
        self.menuSecond.setObjectName("menuSecond")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuSecond.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VIAL 1"))
        self.label_3.setText(_translate("MainWindow", "VIAL 5"))
        self.label_5.setText(_translate("MainWindow", "VIAL 4"))
        self.label_4.setText(_translate("MainWindow", "VIAL 2"))
        self.label_6.setText(_translate("MainWindow", "VIAL 3"))
        self.pushButton.setText(_translate("MainWindow", "GO"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Vial 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vial 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Vial 3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Vial 4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Vial 5"))
        self.label_7.setText(_translate("MainWindow", "MAX TEMP [C]"))
        self.label_8.setText(_translate("MainWindow", "FINAL TEMP [C]"))
        self.label_9.setText(_translate("MainWindow", "RISE TIME [S]"))
        self.label_10.setText(_translate("MainWindow", "DWELL TIME 1 [S]"))
        self.label_11.setText(_translate("MainWindow", "FALL TIME [S]"))
        self.label_12.setText(_translate("MainWindow", "DWELL TIME 2 [S]"))
        self.label_13.setText(_translate("MainWindow", "CEILING TEMP [C]"))
        self.menuMain.setTitle(_translate("MainWindow", "Main "))
        self.menuSecond.setTitle(_translate("MainWindow", "Second"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
